export * from './betting.service';
import { BettingService } from './betting.service';
export * from './coaches.service';
import { CoachesService } from './coaches.service';
export * from './conferences.service';
import { ConferencesService } from './conferences.service';
export * from './draft.service';
import { DraftService } from './draft.service';
export * from './drives.service';
import { DrivesService } from './drives.service';
export * from './games.service';
import { GamesService } from './games.service';
export * from './metrics.service';
import { MetricsService } from './metrics.service';
export * from './players.service';
import { PlayersService } from './players.service';
export * from './plays.service';
import { PlaysService } from './plays.service';
export * from './rankings.service';
import { RankingsService } from './rankings.service';
export * from './ratings.service';
import { RatingsService } from './ratings.service';
export * from './recruiting.service';
import { RecruitingService } from './recruiting.service';
export * from './stats.service';
import { StatsService } from './stats.service';
export * from './teams.service';
import { TeamsService } from './teams.service';
export * from './venues.service';
import { VenuesService } from './venues.service';
export const APIS = [BettingService, CoachesService, ConferencesService, DraftService, DrivesService, GamesService, MetricsService, PlayersService, PlaysService, RankingsService, RatingsService, RecruitingService, StatsService, TeamsService, VenuesService];
