/**
 * College Football Data API
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * OpenAPI spec version: 4.3.2
 * Contact: admin@collegefootballdata.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { Drive } from '../model/drive';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class DrivesService {

    protected basePath = 'https://api.collegefootballdata.com';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Drive data and results
     * Get game drives
     * @param year Year filter
     * @param seasonType Season type filter
     * @param week Week filter
     * @param team Team filter
     * @param offense Offensive team filter
     * @param defense Defensive team filter
     * @param conference Conference filter
     * @param offenseConference Offensive conference filter
     * @param defenseConference Defensive conference filter
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDrives(year: number, seasonType?: string, week?: number, team?: string, offense?: string, defense?: string, conference?: string, offenseConference?: string, defenseConference?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Drive>>;
    public getDrives(year: number, seasonType?: string, week?: number, team?: string, offense?: string, defense?: string, conference?: string, offenseConference?: string, defenseConference?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Drive>>>;
    public getDrives(year: number, seasonType?: string, week?: number, team?: string, offense?: string, defense?: string, conference?: string, offenseConference?: string, defenseConference?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Drive>>>;
    public getDrives(year: number, seasonType?: string, week?: number, team?: string, offense?: string, defense?: string, conference?: string, offenseConference?: string, defenseConference?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (year === null || year === undefined) {
            throw new Error('Required parameter year was null or undefined when calling getDrives.');
        }









        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (seasonType !== undefined && seasonType !== null) {
            queryParameters = queryParameters.set('seasonType', <any>seasonType);
        }
        if (year !== undefined && year !== null) {
            queryParameters = queryParameters.set('year', <any>year);
        }
        if (week !== undefined && week !== null) {
            queryParameters = queryParameters.set('week', <any>week);
        }
        if (team !== undefined && team !== null) {
            queryParameters = queryParameters.set('team', <any>team);
        }
        if (offense !== undefined && offense !== null) {
            queryParameters = queryParameters.set('offense', <any>offense);
        }
        if (defense !== undefined && defense !== null) {
            queryParameters = queryParameters.set('defense', <any>defense);
        }
        if (conference !== undefined && conference !== null) {
            queryParameters = queryParameters.set('conference', <any>conference);
        }
        if (offenseConference !== undefined && offenseConference !== null) {
            queryParameters = queryParameters.set('offenseConference', <any>offenseConference);
        }
        if (defenseConference !== undefined && defenseConference !== null) {
            queryParameters = queryParameters.set('defenseConference', <any>defenseConference);
        }

        let headers = this.defaultHeaders;

        // authentication (ApiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<Drive>>(`${this.basePath}/drives`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
