/**
 * College Football Data API
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * OpenAPI spec version: 4.3.2
 * Contact: admin@collegefootballdata.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { AdvancedGameStat } from '../model/advancedGameStat';
import { AdvancedSeasonStat } from '../model/advancedSeasonStat';
import { TeamSeasonStat } from '../model/teamSeasonStat';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class StatsService {

    protected basePath = 'https://api.collegefootballdata.com';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Advanced team metrics by game
     * Advanced team game stats
     * @param year Year filter (required if no team specified)
     * @param week Week filter
     * @param team Team filter (required if no year specified)
     * @param opponent Opponent filter
     * @param excludeGarbageTime Filter to remove garbage time plays from calculations
     * @param seasonType Season type filter (regular, postseason, or both)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAdvancedTeamGameStats(year?: number, week?: number, team?: string, opponent?: string, excludeGarbageTime?: boolean, seasonType?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<AdvancedGameStat>>;
    public getAdvancedTeamGameStats(year?: number, week?: number, team?: string, opponent?: string, excludeGarbageTime?: boolean, seasonType?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AdvancedGameStat>>>;
    public getAdvancedTeamGameStats(year?: number, week?: number, team?: string, opponent?: string, excludeGarbageTime?: boolean, seasonType?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AdvancedGameStat>>>;
    public getAdvancedTeamGameStats(year?: number, week?: number, team?: string, opponent?: string, excludeGarbageTime?: boolean, seasonType?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {







        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (year !== undefined && year !== null) {
            queryParameters = queryParameters.set('year', <any>year);
        }
        if (week !== undefined && week !== null) {
            queryParameters = queryParameters.set('week', <any>week);
        }
        if (team !== undefined && team !== null) {
            queryParameters = queryParameters.set('team', <any>team);
        }
        if (opponent !== undefined && opponent !== null) {
            queryParameters = queryParameters.set('opponent', <any>opponent);
        }
        if (excludeGarbageTime !== undefined && excludeGarbageTime !== null) {
            queryParameters = queryParameters.set('excludeGarbageTime', <any>excludeGarbageTime);
        }
        if (seasonType !== undefined && seasonType !== null) {
            queryParameters = queryParameters.set('seasonType', <any>seasonType);
        }

        let headers = this.defaultHeaders;

        // authentication (ApiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<AdvancedGameStat>>(`${this.basePath}/stats/game/advanced`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Advanced team metrics by season
     * Advanced team season stats
     * @param year Year filter (required if no team specified)
     * @param team Team filter (required if no year specified)
     * @param excludeGarbageTime Filter to remove garbage time plays from calculations
     * @param startWeek Starting week filter
     * @param endWeek Starting week filter
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAdvancedTeamSeasonStats(year?: number, team?: string, excludeGarbageTime?: boolean, startWeek?: number, endWeek?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<AdvancedSeasonStat>>;
    public getAdvancedTeamSeasonStats(year?: number, team?: string, excludeGarbageTime?: boolean, startWeek?: number, endWeek?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AdvancedSeasonStat>>>;
    public getAdvancedTeamSeasonStats(year?: number, team?: string, excludeGarbageTime?: boolean, startWeek?: number, endWeek?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AdvancedSeasonStat>>>;
    public getAdvancedTeamSeasonStats(year?: number, team?: string, excludeGarbageTime?: boolean, startWeek?: number, endWeek?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (year !== undefined && year !== null) {
            queryParameters = queryParameters.set('year', <any>year);
        }
        if (team !== undefined && team !== null) {
            queryParameters = queryParameters.set('team', <any>team);
        }
        if (excludeGarbageTime !== undefined && excludeGarbageTime !== null) {
            queryParameters = queryParameters.set('excludeGarbageTime', <any>excludeGarbageTime);
        }
        if (startWeek !== undefined && startWeek !== null) {
            queryParameters = queryParameters.set('startWeek', <any>startWeek);
        }
        if (endWeek !== undefined && endWeek !== null) {
            queryParameters = queryParameters.set('endWeek', <any>endWeek);
        }

        let headers = this.defaultHeaders;

        // authentication (ApiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<AdvancedSeasonStat>>(`${this.basePath}/stats/season/advanced`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Team stat categories
     * Stat category list
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getStatCategories(observe?: 'body', reportProgress?: boolean): Observable<Array<string>>;
    public getStatCategories(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<string>>>;
    public getStatCategories(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<string>>>;
    public getStatCategories(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (ApiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<string>>(`${this.basePath}/stats/categories`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Team statistics by season
     * Team season stats
     * @param year Year filter (required if no team specified)
     * @param team Team filter (required if no year specified)
     * @param conference Conference abbreviation filter
     * @param startWeek Starting week filter
     * @param endWeek Starting week filter
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTeamSeasonStats(year?: number, team?: string, conference?: string, startWeek?: number, endWeek?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<TeamSeasonStat>>;
    public getTeamSeasonStats(year?: number, team?: string, conference?: string, startWeek?: number, endWeek?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<TeamSeasonStat>>>;
    public getTeamSeasonStats(year?: number, team?: string, conference?: string, startWeek?: number, endWeek?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<TeamSeasonStat>>>;
    public getTeamSeasonStats(year?: number, team?: string, conference?: string, startWeek?: number, endWeek?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (year !== undefined && year !== null) {
            queryParameters = queryParameters.set('year', <any>year);
        }
        if (team !== undefined && team !== null) {
            queryParameters = queryParameters.set('team', <any>team);
        }
        if (conference !== undefined && conference !== null) {
            queryParameters = queryParameters.set('conference', <any>conference);
        }
        if (startWeek !== undefined && startWeek !== null) {
            queryParameters = queryParameters.set('startWeek', <any>startWeek);
        }
        if (endWeek !== undefined && endWeek !== null) {
            queryParameters = queryParameters.set('endWeek', <any>endWeek);
        }

        let headers = this.defaultHeaders;

        // authentication (ApiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<TeamSeasonStat>>(`${this.basePath}/stats/season`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
