/**
 * College Football Data API
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * OpenAPI spec version: 4.3.2
 * Contact: admin@collegefootballdata.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface GameWeather { 
    id?: number;
    season?: number;
    week?: number;
    seasonType?: string;
    startTime?: string;
    gameIndoors?: boolean;
    homeTeam?: string;
    homeConference?: string;
    awayTeam?: string;
    awayConference?: string;
    venueId?: number;
    venue?: string;
    temperature?: number;
    dewPoint?: number;
    humidity?: number;
    precipitation?: number;
    snowfall?: number;
    windDirection?: number;
    windSpeed?: number;
    pressure?: number;
    weatherConditionCode?: number;
    weatherCondition?: string;
}
