/**
 * College Football Data API
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * OpenAPI spec version: 4.3.2
 * Contact: admin@collegefootballdata.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Player { 
    id?: number;
    firstName?: string;
    lastName?: string;
    team?: string;
    height?: number;
    weight?: number;
    jersey?: number;
    year?: number;
    position?: string;
    homeCity?: string;
    homeState?: string;
    homeCountry?: string;
    homeLatitude?: number;
    homeLongitude?: number;
    homeCountyFips?: string;
    recruitIds?: Array<number>;
}
