/**
 * College Football Data API
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * OpenAPI spec version: 4.3.2
 * Contact: admin@collegefootballdata.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Play { 
    id?: number;
    driveId?: number;
    gameId?: number;
    driveNumber?: number;
    playNumber?: number;
    offense?: string;
    offenseConference?: string;
    offenseScore?: number;
    defense?: string;
    home?: string;
    away?: string;
    defenseConference?: string;
    defenseScore?: number;
    period?: number;
    clock?: any;
    offenseTimeouts?: number;
    defenseTimeouts?: number;
    yardLine?: number;
    yardsToGoal?: number;
    down?: number;
    distance?: number;
    yardsGained?: number;
    scoring?: boolean;
    playType?: string;
    playText?: string;
    ppa?: number;
    wallclock?: string;
}
