/**
 * College Football Data API
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * OpenAPI spec version: 4.3.2
 * Contact: admin@collegefootballdata.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Recruit { 
    id?: number;
    athleteId?: number;
    recruitType?: string;
    year?: number;
    ranking?: number;
    name?: string;
    school?: string;
    committedTo?: string;
    position?: string;
    height?: number;
    weight?: number;
    stars?: number;
    rating?: number;
    city?: string;
    stateProvince?: string;
    country?: string;
    hometownInfo?: any;
}
