/**
 * College Football Data API
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * OpenAPI spec version: 4.3.2
 * Contact: admin@collegefootballdata.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ScoreboardGame { 
    id?: number;
    startDate?: string;
    tv?: string;
    neutralSite?: boolean;
    conferenceGame?: boolean;
    status?: string;
    period?: number;
    clock?: string;
    venue?: any;
    homeTeam?: any;
    awayTeam?: any;
    weather?: any;
    betting?: any;
}
