/**
 * College Football Data API
 * This is an API for accessing all sorts of college football data.  Please note that API keys should be supplied with \"Bearer \" prepended (e.g. \"Bearer your_key\"). API keys can be acquired from the CollegeFootballData.com website.
 *
 * OpenAPI spec version: 4.3.2
 * Contact: admin@collegefootballdata.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Team { 
    id?: number;
    school?: string;
    mascot?: string;
    abbreviation?: string;
    altName1?: string;
    altName2?: string;
    altName3?: string;
    conference?: string;
    division?: string;
    color?: string;
    altColor?: string;
    logos?: Array<string>;
    location?: any;
}
